Add new --source-only-changes option
Signed-off-by: Mattia Rizzolo <mattia@debian.org>

diff --git a/pbuilder-buildpackage b/pbuilder-buildpackage
--- a/pbuilder-buildpackage
+++ b/pbuilder-buildpackage
@@ -128,6 +128,9 @@ log.i "Copying source file"
 copydsc "$PACKAGENAME" "${BUILDPLACE}$BUILDDIR"
 copyinputfile "${BUILDPLACE}$BUILDDIR"
 
+SUBDIR_NAME=$(dsc_get_basename "$PACKAGENAME" "no")
+SUBDIR_NAME=${SUBDIR_NAME//_/-}
+
 log.i "Extracting source"
 if echo "chown $BUILDUSERNAME:$BUILDUSERNAME $BUILDDIR $BUILDDIR/*" | $CHROOTEXEC /bin/bash; then
     : # success
@@ -135,7 +138,7 @@ else
     log.e "pbuilder: Failed chowning to $BUILDUSERNAME:$BUILDUSERNAME"
     exit 1;
 fi
-if echo "( cd $BUILDDIR; env PATH=\"$PATH\" dpkg-source -x $(basename "$PACKAGENAME") )" | $UNSHARE $CHROOTEXEC env $SUTOUSER ; then
+if echo "( cd $BUILDDIR; env PATH=\"$PATH\" dpkg-source -x $(basename "$PACKAGENAME") "$SUBDIR_NAME" )" | $UNSHARE $CHROOTEXEC env $SUTOUSER ; then
     : # success
 else
     log.e "pbuilder: Failed extracting the source"
@@ -155,7 +158,14 @@ log.i "Building the package"
 
 executehooks "A"
 
-DPKG_COMMANDLINE="env PATH=\"$PATH\" HOME=\"$BUILD_HOME\" dpkg-buildpackage -us -uc $DEBBUILDOPTS"
+CHANGES_BASENAME=$(dsc_get_basename "$PACKAGENAME" "yes")
+
+ENV_PREFIX="env PATH=\"$PATH\" HOME=\"$BUILD_HOME\""
+DPKG_COMMANDLINE="$ENV_PREFIX dpkg-buildpackage -us -uc $DEBBUILDOPTS"
+
+if [ "${SOURCE_ONLY_CHANGES}" = "yes" ]; then
+    DPKG_COMMANDLINE="$DPKG_COMMANDLINE && $ENV_PREFIX dpkg-genchanges -S > ../${CHANGES_BASENAME}_source.changes"
+fi
 
 # https://launchpad.net/bugs/816556
 unset DISPLAY
@@ -171,7 +181,7 @@ fi
     if [ -n "$TWICE" ]; then
         DPKG_COMMANDLINE="$DPKG_COMMANDLINE && $DPKG_COMMANDLINE"
     fi
-    DPKG_COMMANDLINE="cd ${BUILDDIR}/*/ && $DPKG_COMMANDLINE"
+    DPKG_COMMANDLINE="cd ${BUILDDIR}/$SUBDIR_NAME/ && $DPKG_COMMANDLINE"
     log.i "Running $DPKG_COMMANDLINE"
     echo "$DPKG_COMMANDLINE" | $UNSHARE $CHROOTEXEC env $SUTOUSER
 ) &
@@ -211,12 +221,41 @@ if [ "$USENETWORK" = "no" ]; then
     copy_local_configuration resolv.conf
 fi
 
+CHANGES_ARCHITECTURE=${HOST_ARCH:-$(dpkg-architecture -qDEB_HOST_ARCH)}
+
+# dpkg pre-1.18.8 generated _$arch.changes even for indep-only builds,
+# so search for both.
+INDEP_CHANGES_FILE="${BUILDPLACE}$BUILDDIR/${CHANGES_BASENAME}_all.changes"
+if [ "${BINARY_ARCH}" = "all" -a -f "${INDEP_CHANGES_FILE}" ]; then
+    ARCH_CHANGES_FILE="$INDEP_CHANGES_FILE"
+else
+    ARCH_CHANGES_FILE="${BUILDPLACE}$BUILDDIR/${CHANGES_BASENAME}_${CHANGES_ARCHITECTURE}.changes"
+
+    if [ ! -f "${ARCH_CHANGES_FILE}" ]; then
+        log.e "Missing changes file: ${ARCH_CHANGES_FILE}"
+        exit 1
+    fi
+fi
+
+SOURCE_CHANGES_FILE="${BUILDPLACE}$BUILDDIR/${CHANGES_BASENAME}_source.changes"
+
+if [ "${SOURCE_ONLY_CHANGES}" = "yes" -a ! -f "${SOURCE_CHANGES_FILE}" ]; then
+    log.e "Missing source-only changes file: ${SOURCE_CHANGES_FILE}"
+    exit 1
+fi
+
 executehooks "B"
 
 if [ -d "${BUILDRESULT}" ]; then
     chown "${BUILDRESULTUID}:${BUILDRESULTGID}" "${BUILDPLACE}$BUILDDIR/"*
     chgrp "${BUILDRESULTGID}" "${BUILDPLACE}$BUILDDIR/"*
-    for FILE in $(get822files "changes" "${BUILDPLACE}$BUILDDIR"/*.changes) ; do
+    if [ "${SOURCE_ONLY_CHANGES}" = "yes" ]; then
+        cp -p "${SOURCE_CHANGES_FILE}" "${BUILDRESULT}"
+        FILES=$( ( get822files "changes" "$ARCH_CHANGES_FILE" && get822files "changes" "$SOURCE_CHANGES_FILE" ) | sort -u)
+    else
+        FILES=$(get822files "changes" "$ARCH_CHANGES_FILE")
+    fi
+    for FILE in $FILES; do
         if [ -f "${FILE}" ]; then
             cp -p "${FILE}" "${BUILDRESULT}" || true
         fi
