fix a whole bunch of warning from shellcheck
There are still quite some, this is a first chunk based on a given patch
applied where i felt confident enough.

Thanks: Herbert Parentes Fortes Neto <hpfn@ig.com.br> for the initial patch-set

diff --git a/pbuilder-unshare-wrapper b/pbuilder-unshare-wrapper
--- a/pbuilder-unshare-wrapper
+++ b/pbuilder-unshare-wrapper
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 die() {
-	echo >&2 E: $2 returned error code $1
+	echo >&2 E: "$2" returned error code "$1"
 	echo >&2 N: Could not set up the loopback interface.
 	exit 1
 }
