pdebuild: make debsign work if only a source build was perfomed and only _source.changes is available
Thanks: Marcin Kulisz <marcin@bashton.com> for the original patch
Closes: #804905

diff --git a/pdebuild b/pdebuild
--- a/pdebuild
+++ b/pdebuild
@@ -33,6 +33,7 @@ PKG_SOURCENAME=$(dpkg-parsechangelog|sed -n 's/^Source: //p')
 PKG_VERSION=$(dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p')
 ARCHITECTURE="${ARCHITECTURE:-$(dpkg-architecture -qDEB_HOST_ARCH)}"
 CHANGES="${PKG_SOURCENAME}_${PKG_VERSION}_${ARCHITECTURE}.changes"
+SOURCE_CHANGES="${PKG_SOURCENAME}_${PKG_VERSION}_source.changes"
 
 if [ -z "${PBUILDER_BUILD_LOGFILE}" ]; then
     PBUILDER_BUILD_LOGFILE="../${PKG_SOURCENAME}_${PKG_VERSION}_${ARCHITECTURE}.build"
@@ -93,8 +94,15 @@ fi
 if [ "${AUTO_DEBSIGN}" = "yes" ]; then
     unset DEBSIGN_PARAM || true
     if [ -n "${DEBSIGN_KEYID}" ]; then
-	DEBSIGN_PARAM[1]="-k${DEBSIGN_KEYID}"
+        DEBSIGN_PARAM[1]="-k${DEBSIGN_KEYID}"
     fi
-    DEBSIGN_PARAM[2]="${BUILDRESULT}/${CHANGES}"
+    if [ -f "${BUILDRESULT}/${CHANGES}" ]; then
+        DEBSIGN_PARAM[2]="${BUILDRESULT}/${CHANGES}"
+    elif [ -f "${BUILDRESULT}/${SOURCE_CHANGES}" ]; then
+        DEBSIGN_PARAM[2]="${BUILDRESULT}/${SOURCE_CHANGES}"
+    else
+        log "E: the .changes file can't be found, debsing not done"
+        exit 1
+    fi
     debsign "${DEBSIGN_PARAM[@]}"
 fi
